import jsPDF from "jspdf";

// Main function that checks what to download
export async function downloadPDF() {
  try {
    const currentPage = window.location.pathname;
    
    if (currentPage.includes('/diet') || currentPage.includes('/diet-')) {
      await downloadDietPDF();
    } else if (currentPage.includes('/workout') || currentPage.includes('/workout-')) {
      await downloadWorkoutPDF();
    } else {
      const dietPlanStr = localStorage.getItem('dietPlan');
      const workoutPlanStr = localStorage.getItem('workoutPlan');
      
      if (dietPlanStr && workoutPlanStr) {
        await downloadCombinedPDF();
      } else if (dietPlanStr) {
        await downloadDietPDF();
      } else if (workoutPlanStr) {
        await downloadWorkoutPDF();
      } else {
        alert("Please generate a plan first.");
      }
    }
  } catch (error) {
    console.error("PDF generation error:", error);
    alert("Failed to generate PDF. Please try again.");
  }
}

// Separate function for diet-only PDF
export async function downloadDietPDF() {
  const dietPlanStr = localStorage.getItem('dietPlan');
  
  if (!dietPlanStr) {
    alert("Please generate a diet plan first.");
    return;
  }

  const dietPlan = JSON.parse(dietPlanStr);
  const pdf = new jsPDF("p", "mm", "a4");
  
  addDietCoverPage(pdf);
  pdf.addPage();
  addDietPlanContent(pdf, dietPlan);
  
  pdf.save("SwasthX-Diet-Plan.pdf");
}

// Separate function for workout-only PDF
export async function downloadWorkoutPDF() {
  const workoutPlanStr = localStorage.getItem('workoutPlan');
  
  if (!workoutPlanStr) {
    alert("Please generate a workout plan first.");
    return;
  }

  const workoutPlan = JSON.parse(workoutPlanStr);
  const pdf = new jsPDF("p", "mm", "a4");
  
  addWorkoutCoverPage(pdf);
  pdf.addPage();
  addWorkoutPlanContent(pdf, workoutPlan);
  
  pdf.save("SwasthX-Workout-Plan.pdf");
}

// Combined function (if needed)
async function downloadCombinedPDF() {
  const dietPlanStr = localStorage.getItem('dietPlan');
  const workoutPlanStr = localStorage.getItem('workoutPlan');
  
  if (!dietPlanStr && !workoutPlanStr) {
    alert("Please generate at least one plan first.");
    return;
  }

  const dietPlan = dietPlanStr ? JSON.parse(dietPlanStr) : null;
  const workoutPlan = workoutPlanStr ? JSON.parse(workoutPlanStr) : null;
  const pdf = new jsPDF("p", "mm", "a4");
  
  addCombinedCoverPage(pdf, dietPlan, workoutPlan);
  
  if (dietPlan) {
    pdf.addPage();
    addDietPlanContent(pdf, dietPlan);
  }
  
  if (workoutPlan) {
    pdf.addPage();
    addWorkoutPlanContent(pdf, workoutPlan);
  }
  
  let filename = "SwasthX-Plan";
  if (dietPlan && workoutPlan) {
    filename = "SwasthX-Diet-Workout-Plan";
  } else if (dietPlan) {
    filename = "SwasthX-Diet-Plan";
  } else if (workoutPlan) {
    filename = "SwasthX-Workout-Plan";
  }
  
  pdf.save(`${filename}.pdf`);
}

function addDietCoverPage(pdf: jsPDF) {
  const pageWidth = pdf.internal.pageSize.width;
  const centerX = pageWidth / 2;
  
  // Title
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.text("Your Personalized", centerX, 60, { align: "center" });
  pdf.text("Diet Plan", centerX, 75, { align: "center" });
  
  // Logo/App Name
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "normal");
  pdf.text("Generated by", centerX, 110, { align: "center" });
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text("SwasthX", centerX, 125, { align: "center" });
  
  // Plan Summary
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text("Personalized nutrition plan", centerX, 160, { align: "center" });
  
  // Message
  pdf.setFontSize(14);
  pdf.text("Remember:", centerX, 190, { align: "center" });
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Consistency beats motivation", centerX, 205, { align: "center" });
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text("Follow the plan for 4–6 weeks for best results", centerX, 220, { align: "center" });
  
  // Date
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  pdf.setFontSize(12);
  pdf.text(`Generated on: ${dateStr}`, 20, 280);
}

function addWorkoutCoverPage(pdf: jsPDF) {
  const pageWidth = pdf.internal.pageSize.width;
  const centerX = pageWidth / 2;
  
  // Title
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.text("Your Personalized", centerX, 60, { align: "center" });
  pdf.text("Workout Plan", centerX, 75, { align: "center" });
  
  // Logo/App Name
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "normal");
  pdf.text("Generated by", centerX, 110, { align: "center" });
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text("SwasthX", centerX, 125, { align: "center" });
  
  // Plan Summary
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text("Custom workout schedule", centerX, 160, { align: "center" });
  
  // Message
  pdf.setFontSize(14);
  pdf.text("Remember:", centerX, 190, { align: "center" });
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Consistency beats motivation", centerX, 205, { align: "center" });
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text("Follow the plan for 4–6 weeks for best results", centerX, 220, { align: "center" });
  
  // Date
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  pdf.setFontSize(12);
  pdf.text(`Generated on: ${dateStr}`, 20, 280);
}

function addCombinedCoverPage(pdf: jsPDF, dietPlan: any, workoutPlan: any) {
  const pageWidth = pdf.internal.pageSize.width;
  const centerX = pageWidth / 2;
  
  let titleLine1 = "Your Personalized";
  let titleLine2 = "";
  
  if (dietPlan && workoutPlan) {
    titleLine2 = "Diet & Workout Plan";
  } else if (dietPlan) {
    titleLine2 = "Diet Plan";
  } else if (workoutPlan) {
    titleLine2 = "Workout Plan";
  }
  
  // Title
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.text(titleLine1, centerX, 60, { align: "center" });
  pdf.text(titleLine2, centerX, 75, { align: "center" });
  
  // Logo/App Name
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "normal");
  pdf.text("Generated by", centerX, 110, { align: "center" });
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text("SwasthX", centerX, 125, { align: "center" });
  
  let planSummary = "";
  if (dietPlan && workoutPlan) {
    planSummary = "Complete diet and workout plan";
  } else if (dietPlan) {
    planSummary = "Personalized nutrition plan";
  } else if (workoutPlan) {
    planSummary = "Custom workout schedule";
  }
  
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text(planSummary, centerX, 160, { align: "center" });
  
  // Message
  pdf.setFontSize(14);
  pdf.text("Remember:", centerX, 190, { align: "center" });
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Consistency beats motivation", centerX, 205, { align: "center" });
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text("Follow the plan for 4–6 weeks for best results", centerX, 220, { align: "center" });
  
  // Date
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  pdf.setFontSize(12);
  pdf.text(`Generated on: ${dateStr}`, 20, 280);
}

function addDietPlanContent(pdf: jsPDF, plan: any) {
  let yPos = 20;
  const pageWidth = pdf.internal.pageSize.width;
  const margin = 20;
  
  // Diet Plan Title
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("Diet Plan", margin, yPos);
  yPos += 15;
  
  // Add horizontal line
  pdf.setDrawColor(0, 150, 0);
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  // Daily Calories
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Daily Calories:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.totalCalories?.min || 0} – ${plan.totalCalories?.max || 0} kcal`, margin + 50, yPos);
  yPos += 10;
  
  // Per Meal Calories
  pdf.setFont("helvetica", "bold");
  pdf.text("Per Meal:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.perMeal?.calories?.min || 0} – ${plan.perMeal?.calories?.max || 0} kcal`, margin + 50, yPos);
  yPos += 15;
  
  // Macronutrients Section
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Macronutrients", margin, yPos);
  yPos += 10;
  
  // Protein
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.text("Protein:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.proteinG?.min || 0} – ${plan.proteinG?.max || 0} grams`, margin + 40, yPos);
  yPos += 8;
  
  // Carbs
  pdf.setFont("helvetica", "bold");
  pdf.text("Carbohydrates:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.carbsG?.min || 0} – ${plan.carbsG?.max || 0} grams`, margin + 40, yPos);
  yPos += 8;
  
  // Fat
  pdf.setFont("helvetica", "bold");
  pdf.text("Fat:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.fatG?.min || 0} – ${plan.fatG?.max || 0} grams`, margin + 40, yPos);
  yPos += 15;
  
  // Meal Suggestions Section - Now handling 6 meals
  if (plan.meals && typeof plan.meals === 'object') {
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Daily Meal Structure", margin, yPos);
    yPos += 10;
    
    // Define meal order and labels for 6-meal structure
    const mealOrder = ['BREAKFAST', 'SNACK1', 'LUNCH', 'SNACK2', 'DINNER', 'SNACK3', 'SNACK'];
    const mealLabels: Record<string, string> = {
      BREAKFAST: "Breakfast",
      LUNCH: "Lunch",
      DINNER: "Dinner",
      SNACK: "Snack",
      SNACK1: "Morning Snack",
      SNACK2: "Afternoon Snack",
      SNACK3: "Evening Snack"
    };
    
    let mealCount = 0;
    
    for (const mealKey of mealOrder) {
      const mealData = plan.meals[mealKey];
      if (mealData) {
        mealCount++;
        
        // Check if we need a new page
        if (yPos > 250) {
          pdf.addPage();
          yPos = 20;
        }
        
        // Meal header with count
        pdf.setFontSize(14);
        pdf.setFont("helvetica", "bold");
        pdf.text(`Meal ${mealCount}: ${mealLabels[mealKey] || mealKey}`, margin, yPos);
        yPos += 8;
        
        // Meal title
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "normal");
        pdf.text(`${mealData.title || "Custom meal"}`, margin + 5, yPos);
        yPos += 8;
        
        // Nutrition facts
        pdf.text(`Calories: ${mealData.calories || 0} kcal`, margin + 10, yPos);
        yPos += 7;
        
        pdf.text(`Protein: ${mealData.proteinG || 0} g`, margin + 10, yPos);
        yPos += 7;
        
        pdf.text(`Carbohydrates: ${mealData.carbsG || 0} g`, margin + 10, yPos);
        yPos += 7;
        
        pdf.text(`Fat: ${mealData.fatG || 0} g`, margin + 10, yPos);
        yPos += 7;
        
        // Ingredients with better formatting
        if (mealData.ingredients) {
          pdf.setFont("helvetica", "bold");
          pdf.text(`Ingredients:`, margin + 10, yPos);
          yPos += 7;
          
          pdf.setFont("helvetica", "normal");
          // Split ingredients by semicolon or comma
          const ingredients = mealData.ingredients.split(/[;,]/).map((ing: string) => ing.trim()).filter(Boolean);
          
          if (ingredients.length > 0) {
            for (const ingredient of ingredients) {
              if (yPos > 270) {
                pdf.addPage();
                yPos = 20;
              }
              pdf.text(`• ${ingredient}`, margin + 15, yPos);
              yPos += 7;
            }
          } else {
            pdf.text(mealData.ingredients, margin + 15, yPos);
            yPos += 7;
          }
        }
        
        yPos += 10; // Space between meals
        
        // Add a subtle separator line between meals (except after the last one)
        if (mealCount < Object.values(plan.meals).filter(Boolean).length) {
          pdf.setDrawColor(200, 200, 200);
          pdf.setLineWidth(0.2);
          pdf.line(margin, yPos - 5, pageWidth - margin, yPos - 5);
        }
      }
    }
    
    // Add total summary at the end
    if (plan.totals) {
      if (yPos > 220) {
        pdf.addPage();
        yPos = 20;
      }
      
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("Daily Totals:", margin, yPos);
      yPos += 10;
      
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");
      pdf.text(`Total Calories: ${plan.totals.calories || 0} kcal`, margin + 10, yPos);
      yPos += 7;
      pdf.text(`Total Protein: ${plan.totals.protein || 0} g`, margin + 10, yPos);
      yPos += 7;
      pdf.text(`Total Carbohydrates: ${plan.totals.carbs || 0} g`, margin + 10, yPos);
      yPos += 7;
      pdf.text(`Total Fat: ${plan.totals.fat || 0} g`, margin + 10, yPos);
      yPos += 10;
    }
  }
  
  // Add "End of Diet Plan" marker
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "italic");
  pdf.text("— End of Diet Plan —", pageWidth / 2, 285, { align: "center" });
}

function addWorkoutPlanContent(pdf: jsPDF, plan: any) {
  let yPos = 20;
  const pageWidth = pdf.internal.pageSize.width;
  const margin = 20;
  
  // Workout Plan Title
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("Workout Plan", margin, yPos);
  yPos += 15;
  
  // Add horizontal line
  pdf.setDrawColor(0, 100, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  // Workout Summary
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.text("Goal:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(formatGoal(plan.goal), margin + 20, yPos);
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Level:", margin + 80, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(formatFitnessLevel(plan.fitnessLevel), margin + 100, yPos);
  yPos += 8;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Days/Week:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.daysPerWeek || 0}`, margin + 35, yPos);
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Location:", margin + 80, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(plan.location === "GYM" ? "Gym" : "Home", margin + 100, yPos);
  yPos += 15;
  
  // Check if days exist
  if (!plan.days || !Array.isArray(plan.days) || plan.days.length === 0) {
    pdf.setFontSize(12);
    pdf.text("No workout days planned.", margin, yPos);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "italic");
    pdf.text("— End of Workout Plan —", pageWidth / 2, 285, { align: "center" });
    return;
  }
  
  // Add each workout day
  for (let i = 0; i < plan.days.length; i++) {
    const day = plan.days[i];
    
    // Check if we need a new page before adding a new day
    if (yPos > 220) {
      pdf.addPage();
      yPos = 20;
      
      // Add continuation header
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("Workout Plan (continued)", margin, yPos);
      yPos += 15;
    }
    
    // Day Header
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text(`Day ${i + 1}: ${day.dayLabel || ''}`, margin, yPos);
    yPos += 8;
    
    // Focus
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text("Focus:", margin, yPos);
    pdf.setFont("helvetica", "normal");
    pdf.text(day.focus || '', margin + 25, yPos);
    yPos += 10;
    
    // Warm-up Section
    if (day.warmup && day.warmup.length > 0) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Warm-up:", margin, yPos);
      yPos += 8;
      
      pdf.setFont("helvetica", "normal");
      day.warmup.forEach((exercise: string, index: number) => {
        pdf.text(`${index + 1}. ${exercise}`, margin + 5, yPos);
        yPos += 7;
        
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "italic");
          pdf.text("(continued...)", margin, yPos);
          yPos += 10;
          pdf.setFontSize(12);
          pdf.setFont("helvetica", "normal");
        }
      });
      yPos += 5;
    }
    
    // Exercises Section
    if (day.exercises && day.exercises.length > 0) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Exercises:", margin, yPos);
      yPos += 8;
      
      pdf.setFont("helvetica", "normal");
      day.exercises.forEach((ex: any, index: number) => {
        const exerciseText = `${index + 1}. ${ex.name} (${ex.muscleGroup || ''})`;
        pdf.text(exerciseText, margin + 5, yPos);
        yPos += 7;
        
        pdf.text(`   Sets: ${ex.sets || 0} | Reps/Time: ${ex.repsOrTime || ''}`, margin + 10, yPos);
        yPos += 7;
        
        if (ex.equipment && ex.equipment !== "Bodyweight") {
          pdf.text(`   Equipment: ${ex.equipment}`, margin + 10, yPos);
          yPos += 7;
        }
        
        if (ex.notes) {
          pdf.text(`   Notes: ${ex.notes}`, margin + 10, yPos);
          yPos += 7;
        }
        
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "italic");
          pdf.text("(continued...)", margin, yPos);
          yPos += 10;
          pdf.setFontSize(12);
          pdf.setFont("helvetica", "normal");
        }
      });
      yPos += 5;
    }
    
    // Cool-down Section
    if (day.cooldown && day.cooldown.length > 0) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Cool-down:", margin, yPos);
      yPos += 8;
      
      pdf.setFont("helvetica", "normal");
      day.cooldown.forEach((exercise: string, index: number) => {
        pdf.text(`${index + 1}. ${exercise}`, margin + 5, yPos);
        yPos += 7;
        
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "italic");
          pdf.text("(continued...)", margin, yPos);
          yPos += 10;
          pdf.setFontSize(12);
          pdf.setFont("helvetica", "normal");
        }
      });
      yPos += 5;
    }
    
    // Add separation between days (unless last day)
    if (i < plan.days.length - 1) {
      pdf.setDrawColor(200, 200, 200);
      pdf.setLineWidth(0.2);
      pdf.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 10;
    }
  }
  
  // Add "End of Workout Plan" marker
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "italic");
  pdf.text("— End of Workout Plan —", pageWidth / 2, 285, { align: "center" });
}

// Helper functions
function formatGoal(goal: string): string {
  const goalMap: { [key: string]: string } = {
    "WEIGHT_LOSS": "Weight Loss",
    "MUSCLE_GAIN": "Muscle Gain",
    "MAINTENANCE": "Maintenance",
    "ENDURANCE": "Endurance"
  };
  return goalMap[goal] || goal;
}

function formatFitnessLevel(level: string): string {
  const levelMap: { [key: string]: string } = {
    "BEGINNER": "Beginner",
    "INTERMEDIATE": "Intermediate",
    "ADVANCED": "Advanced"
  };
  return levelMap[level] || level;
}