import jsPDF from "jspdf";

type ToastFn = (message: string, kind?: "success" | "error" | "info") => void;

// PDF generation runs client-side and outside React, so callers pass their
// showToast handle in rather than this module depending on the Toast context.
export async function downloadPDF(notify: ToastFn) {
  try {
    const currentPage = window.location.pathname;

    if (currentPage.includes('/diet')) {
      await downloadDietPDF(notify);
    } else if (currentPage.includes('/workout')) {
      await downloadWorkoutPDF(notify);
    } else {
      const dietPlanStr = localStorage.getItem('dietPlan');
      const workoutPlanStr = localStorage.getItem('workoutPlan');

      if (dietPlanStr && workoutPlanStr) {
        await downloadCombinedPDF(notify);
      } else if (dietPlanStr) {
        await downloadDietPDF(notify);
      } else if (workoutPlanStr) {
        await downloadWorkoutPDF(notify);
      } else {
        notify("Please generate a plan first.", "error");
      }
    }
  } catch (error) {
    console.error("PDF generation error:", error);
    notify("Failed to generate PDF. Please try again.", "error");
  }
}

export async function downloadDietPDF(notify?: ToastFn) {
  const dietPlanStr = localStorage.getItem('dietPlan');

  if (!dietPlanStr) {
    notify?.("Please generate a diet plan first.", "error");
    return;
  }

  const dietPlan = JSON.parse(dietPlanStr);
  const pdf = new jsPDF("p", "mm", "a4");

  addCoverPage(pdf, { title: "Your Personalized\nDiet Plan", summary: "Personalized nutrition plan" });
  pdf.addPage();
  addDietPlanContent(pdf, dietPlan);

  pdf.save("SwasthX-Diet-Plan.pdf");
  notify?.("Diet plan PDF downloaded.", "success");
}

export async function downloadWorkoutPDF(notify?: ToastFn) {
  const workoutPlanStr = localStorage.getItem('workoutPlan');

  if (!workoutPlanStr) {
    notify?.("Please generate a workout plan first.", "error");
    return;
  }

  const workoutPlan = JSON.parse(workoutPlanStr);
  const pdf = new jsPDF("p", "mm", "a4");

  addCoverPage(pdf, { title: "Your Personalized\nWorkout Plan", summary: "Custom workout schedule" });
  pdf.addPage();
  addWorkoutPlanContent(pdf, workoutPlan);

  pdf.save("SwasthX-Workout-Plan.pdf");
  notify?.("Workout plan PDF downloaded.", "success");
}

async function downloadCombinedPDF(notify?: ToastFn) {
  const dietPlanStr = localStorage.getItem('dietPlan');
  const workoutPlanStr = localStorage.getItem('workoutPlan');

  if (!dietPlanStr && !workoutPlanStr) {
    notify?.("Please generate at least one plan first.", "error");
    return;
  }

  const dietPlan = dietPlanStr ? JSON.parse(dietPlanStr) : null;
  const workoutPlan = workoutPlanStr ? JSON.parse(workoutPlanStr) : null;
  const pdf = new jsPDF("p", "mm", "a4");

  const titleLine2 = dietPlan && workoutPlan ? "Diet & Workout Plan" : dietPlan ? "Diet Plan" : "Workout Plan";
  const summary =
    dietPlan && workoutPlan
      ? "Complete diet and workout plan"
      : dietPlan
      ? "Personalized nutrition plan"
      : "Custom workout schedule";
  addCoverPage(pdf, { title: `Your Personalized\n${titleLine2}`, summary });

  if (dietPlan) {
    pdf.addPage();
    addDietPlanContent(pdf, dietPlan);
  }

  if (workoutPlan) {
    pdf.addPage();
    addWorkoutPlanContent(pdf, workoutPlan);
  }

  let filename = "SwasthX-Plan";
  if (dietPlan && workoutPlan) {
    filename = "SwasthX-Diet-Workout-Plan";
  } else if (dietPlan) {
    filename = "SwasthX-Diet-Plan";
  } else if (workoutPlan) {
    filename = "SwasthX-Workout-Plan";
  }

  pdf.save(`${filename}.pdf`);
  notify?.("PDF downloaded.", "success");
}

function addCoverPage(pdf: jsPDF, { title, summary }: { title: string; summary: string }) {
  const pageWidth = pdf.internal.pageSize.width;
  const centerX = pageWidth / 2;

  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  title.split("\n").forEach((line, i) => {
    pdf.text(line, centerX, 60 + i * 15, { align: "center" });
  });

  pdf.setFontSize(18);
  pdf.setFont("helvetica", "normal");
  pdf.text("Generated by", centerX, 110, { align: "center" });
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text("SwasthX", centerX, 125, { align: "center" });

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text(summary, centerX, 160, { align: "center" });

  pdf.setFontSize(14);
  pdf.text("Remember:", centerX, 190, { align: "center" });
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Consistency beats motivation", centerX, 205, { align: "center" });
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text("Follow the plan for 4-6 weeks for best results", centerX, 220, { align: "center" });

  const today = new Date();
  const dateStr = today.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  pdf.setFontSize(12);
  pdf.text(`Generated on: ${dateStr}`, 20, 280);
}

function addDietPlanContent(pdf: jsPDF, plan: any) {
  let yPos = 20;
  const pageWidth = pdf.internal.pageSize.width;
  const margin = 20;
  
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("Diet Plan", margin, yPos);
  yPos += 15;
  
  pdf.setDrawColor(0, 150, 0);
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Daily Calories:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.totalCalories?.min || 0} – ${plan.totalCalories?.max || 0} kcal`, margin + 50, yPos);
  yPos += 10;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Per Meal:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.perMeal?.calories?.min || 0} – ${plan.perMeal?.calories?.max || 0} kcal`, margin + 50, yPos);
  yPos += 15;
  
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Macronutrients", margin, yPos);
  yPos += 10;
  
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.text("Protein:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.proteinG?.min || 0} – ${plan.proteinG?.max || 0} grams`, margin + 40, yPos);
  yPos += 8;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Carbohydrates:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.carbsG?.min || 0} – ${plan.carbsG?.max || 0} grams`, margin + 40, yPos);
  yPos += 8;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Fat:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.fatG?.min || 0} – ${plan.fatG?.max || 0} grams`, margin + 40, yPos);
  yPos += 15;
  
  if (plan.meals && typeof plan.meals === 'object') {
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Daily Meal Structure", margin, yPos);
    yPos += 10;
    
    const mealOrder = ['BREAKFAST', 'SNACK1', 'LUNCH', 'SNACK2', 'DINNER', 'SNACK3', 'SNACK'];
    const mealLabels: Record<string, string> = {
      BREAKFAST: "Breakfast",
      LUNCH: "Lunch",
      DINNER: "Dinner",
      SNACK: "Snack",
      SNACK1: "Morning Snack",
      SNACK2: "Afternoon Snack",
      SNACK3: "Evening Snack"
    };
    
    let mealCount = 0;
    
    for (const mealKey of mealOrder) {
      const mealData = plan.meals[mealKey];
      if (mealData) {
        mealCount++;
        
        if (yPos > 250) {
          pdf.addPage();
          yPos = 20;
        }
        
        pdf.setFontSize(14);
        pdf.setFont("helvetica", "bold");
        pdf.text(`Meal ${mealCount}: ${mealLabels[mealKey] || mealKey}`, margin, yPos);
        yPos += 8;
        
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "normal");
        pdf.text(`${mealData.title || "Custom meal"}`, margin + 5, yPos);
        yPos += 8;
        
        pdf.text(`Calories: ${mealData.calories || 0} kcal`, margin + 10, yPos);
        yPos += 7;
        
        pdf.text(`Protein: ${mealData.proteinG || 0} g`, margin + 10, yPos);
        yPos += 7;
        
        pdf.text(`Carbohydrates: ${mealData.carbsG || 0} g`, margin + 10, yPos);
        yPos += 7;
        
        pdf.text(`Fat: ${mealData.fatG || 0} g`, margin + 10, yPos);
        yPos += 7;
        
        if (mealData.ingredients) {
          pdf.setFont("helvetica", "bold");
          pdf.text(`Ingredients:`, margin + 10, yPos);
          yPos += 7;
          
          pdf.setFont("helvetica", "normal");
          const ingredients = mealData.ingredients.split(/[;,]/).map((ing: string) => ing.trim()).filter(Boolean);
          
          if (ingredients.length > 0) {
            for (const ingredient of ingredients) {
              if (yPos > 270) {
                pdf.addPage();
                yPos = 20;
              }
              pdf.text(`• ${ingredient}`, margin + 15, yPos);
              yPos += 7;
            }
          } else {
            pdf.text(mealData.ingredients, margin + 15, yPos);
            yPos += 7;
          }
        }
        
        yPos += 10; // Space between meals
        
        if (mealCount < Object.values(plan.meals).filter(Boolean).length) {
          pdf.setDrawColor(200, 200, 200);
          pdf.setLineWidth(0.2);
          pdf.line(margin, yPos - 5, pageWidth - margin, yPos - 5);
        }
      }
    }
    
    if (plan.totals) {
      if (yPos > 220) {
        pdf.addPage();
        yPos = 20;
      }
      
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("Daily Totals:", margin, yPos);
      yPos += 10;
      
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");
      pdf.text(`Total Calories: ${plan.totals.calories || 0} kcal`, margin + 10, yPos);
      yPos += 7;
      pdf.text(`Total Protein: ${plan.totals.protein || 0} g`, margin + 10, yPos);
      yPos += 7;
      pdf.text(`Total Carbohydrates: ${plan.totals.carbs || 0} g`, margin + 10, yPos);
      yPos += 7;
      pdf.text(`Total Fat: ${plan.totals.fat || 0} g`, margin + 10, yPos);
      yPos += 10;
    }
  }
  
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "italic");
  pdf.text("— End of Diet Plan —", pageWidth / 2, 285, { align: "center" });
}

function addWorkoutPlanContent(pdf: jsPDF, plan: any) {
  let yPos = 20;
  const pageWidth = pdf.internal.pageSize.width;
  const margin = 20;
  
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("Workout Plan", margin, yPos);
  yPos += 15;
  
  pdf.setDrawColor(0, 100, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.text("Goal:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(formatGoal(plan.goal), margin + 20, yPos);
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Level:", margin + 80, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(formatFitnessLevel(plan.fitnessLevel), margin + 100, yPos);
  yPos += 8;
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Days/Week:", margin, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${plan.daysPerWeek || 0}`, margin + 35, yPos);
  
  pdf.setFont("helvetica", "bold");
  pdf.text("Location:", margin + 80, yPos);
  pdf.setFont("helvetica", "normal");
  pdf.text(plan.location === "GYM" ? "Gym" : "Home", margin + 100, yPos);
  yPos += 15;
  
  if (!plan.days || !Array.isArray(plan.days) || plan.days.length === 0) {
    pdf.setFontSize(12);
    pdf.text("No workout days planned.", margin, yPos);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "italic");
    pdf.text("— End of Workout Plan —", pageWidth / 2, 285, { align: "center" });
    return;
  }
  
  for (let i = 0; i < plan.days.length; i++) {
    const day = plan.days[i];
    
    if (yPos > 220) {
      pdf.addPage();
      yPos = 20;
      
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("Workout Plan (continued)", margin, yPos);
      yPos += 15;
    }
    
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text(`Day ${i + 1}: ${day.dayLabel || ''}`, margin, yPos);
    yPos += 8;
    
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text("Focus:", margin, yPos);
    pdf.setFont("helvetica", "normal");
    pdf.text(day.focus || '', margin + 25, yPos);
    yPos += 10;
    
    if (day.warmup && day.warmup.length > 0) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Warm-up:", margin, yPos);
      yPos += 8;
      
      pdf.setFont("helvetica", "normal");
      day.warmup.forEach((exercise: string, index: number) => {
        pdf.text(`${index + 1}. ${exercise}`, margin + 5, yPos);
        yPos += 7;
        
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "italic");
          pdf.text("(continued...)", margin, yPos);
          yPos += 10;
          pdf.setFontSize(12);
          pdf.setFont("helvetica", "normal");
        }
      });
      yPos += 5;
    }
    
    if (day.exercises && day.exercises.length > 0) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Exercises:", margin, yPos);
      yPos += 8;
      
      pdf.setFont("helvetica", "normal");
      day.exercises.forEach((ex: any, index: number) => {
        const exerciseText = `${index + 1}. ${ex.name} (${ex.muscleGroup || ''})`;
        pdf.text(exerciseText, margin + 5, yPos);
        yPos += 7;
        
        pdf.text(`   Sets: ${ex.sets || 0} | Reps/Time: ${ex.repsOrTime || ''}`, margin + 10, yPos);
        yPos += 7;
        
        if (ex.equipment && ex.equipment !== "Bodyweight") {
          pdf.text(`   Equipment: ${ex.equipment}`, margin + 10, yPos);
          yPos += 7;
        }
        
        if (ex.notes) {
          pdf.text(`   Notes: ${ex.notes}`, margin + 10, yPos);
          yPos += 7;
        }
        
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "italic");
          pdf.text("(continued...)", margin, yPos);
          yPos += 10;
          pdf.setFontSize(12);
          pdf.setFont("helvetica", "normal");
        }
      });
      yPos += 5;
    }
    
    if (day.cooldown && day.cooldown.length > 0) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Cool-down:", margin, yPos);
      yPos += 8;
      
      pdf.setFont("helvetica", "normal");
      day.cooldown.forEach((exercise: string, index: number) => {
        pdf.text(`${index + 1}. ${exercise}`, margin + 5, yPos);
        yPos += 7;
        
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "italic");
          pdf.text("(continued...)", margin, yPos);
          yPos += 10;
          pdf.setFontSize(12);
          pdf.setFont("helvetica", "normal");
        }
      });
      yPos += 5;
    }
    
    if (i < plan.days.length - 1) {
      pdf.setDrawColor(200, 200, 200);
      pdf.setLineWidth(0.2);
      pdf.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 10;
    }
  }
  
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "italic");
  pdf.text("— End of Workout Plan —", pageWidth / 2, 285, { align: "center" });
}

function formatGoal(goal: string): string {
  const goalMap: { [key: string]: string } = {
    "WEIGHT_LOSS": "Weight Loss",
    "MUSCLE_GAIN": "Muscle Gain",
    "MAINTENANCE": "Maintenance",
  };
  return goalMap[goal] || goal;
}

function formatFitnessLevel(level: string): string {
  const levelMap: { [key: string]: string } = {
    "BEGINNER": "Beginner",
    "INTERMEDIATE": "Intermediate",
    "ADVANCED": "Advanced"
  };
  return levelMap[level] || level;
}